export type CenterType = "hemocentro" | "banco_sangue" | "posto_coleta" | "hospital_com_coleta";
export type Management = "publico" | "privado" | "filantropico";
export type VerificationStatus = "verified" | "pending" | "outdated";
export interface TimeRange { start: string; end: string }
export interface WeeklySchedule { weekdays?: TimeRange; saturday?: TimeRange; sunday?: TimeRange; holidays?: TimeRange }

export interface DonationCenter {
  id: string; name: string; institutionName: string; donationLocationName?: string;
  type: CenterType; management: Management;
  address: { street: string; number?: string; complement?: string; neighborhood: string; city: string; state: "SP"; postalCode?: string };
  fullAddress: string; city: string; neighborhood: string; postalCode?: string;
  coordinates: { latitude: number; longitude: number };
  contact: { phone?: string; whatsapp?: string; website?: string };
  donation: {
    bloodDonation: boolean; plateletDonation?: boolean; appointmentRequired?: boolean; appointmentRecommended?: boolean;
    appointmentUrl?: string; openingHours?: string; schedule?: WeeklySchedule;
    saturdayService?: boolean; sundayService?: boolean; holidayService?: boolean;
    parkingAvailable?: boolean; freeParkingForDonors?: boolean;
  };
  source: { institutionName: string; officialUrl: string; lastVerifiedAt: string };
  verificationStatus: VerificationStatus; active: boolean; createdAt: string; updatedAt: string;
}

const VERIFIED = "2026-08-28";
const CREATED = "2026-08-28";
const PROSANGUE = "https://www.portal.prosangue.sp.gov.br/fps/institucional/horarios_de_atendimentos_e_enderecos";
const COLSAN = "https://colsan.org.br/doador/locais-para-doacao-de-sangue/";
const row = (center: Omit<DonationCenter, "verificationStatus" | "active" | "createdAt" | "updatedAt">): DonationCenter => ({ ...center, verificationStatus: "verified", active: true, createdAt: CREATED, updatedAt: VERIFIED });
const address = (street: string, number: string, neighborhood: string, city: string, postalCode?: string, complement?: string) => ({ street, number, neighborhood, city, postalCode, complement, state: "SP" as const });

export const DONATION_CENTERS: DonationCenter[] = [
  row({ id:"pro-sangue-clinicas", name:"Pró-Sangue — Posto Clínicas", institutionName:"Fundação Pró-Sangue", type:"posto_coleta", management:"publico", address:address("Av. Dr. Enéas Carvalho de Aguiar","155","Cerqueira César","São Paulo","05403-000","1º andar"), fullAddress:"Av. Dr. Enéas Carvalho de Aguiar, 155, 1º andar — Cerqueira César, São Paulo/SP", city:"São Paulo", neighborhood:"Cerqueira César", postalCode:"05403-000", coordinates:{latitude:-23.5553884,longitude:-46.6725799}, contact:{website:PROSANGUE}, donation:{bloodDonation:true, appointmentRecommended:true, appointmentUrl:"https://prosangue.hubglobe.com/entrar", openingHours:"Consulte o horário oficial."}, source:{institutionName:"Fundação Pró-Sangue",officialUrl:PROSANGUE,lastVerifiedAt:VERIFIED} }),
  row({ id:"pro-sangue-dante", name:"Pró-Sangue — Posto Dante Pazzanese", institutionName:"Fundação Pró-Sangue", type:"posto_coleta", management:"publico", address:address("Av. Dr. Dante Pazzanese","500","Ibirapuera","São Paulo","04012-909"), fullAddress:"Av. Dr. Dante Pazzanese, 500 — Ibirapuera, São Paulo/SP", city:"São Paulo", neighborhood:"Ibirapuera", postalCode:"04012-909", coordinates:{latitude:-23.5847183,longitude:-46.6515992}, contact:{website:PROSANGUE}, donation:{bloodDonation:true, appointmentRecommended:true, appointmentUrl:"https://prosangue.hubglobe.com/entrar", openingHours:"Consulte o horário oficial."}, source:{institutionName:"Fundação Pró-Sangue",officialUrl:PROSANGUE,lastVerifiedAt:VERIFIED} }),
  row({ id:"pro-sangue-mandaqui", name:"Pró-Sangue — Posto Mandaqui", institutionName:"Fundação Pró-Sangue", type:"posto_coleta", management:"publico", address:address("Rua Voluntários da Pátria","4227","Mandaqui","São Paulo","02401-400"), fullAddress:"Rua Voluntários da Pátria, 4.227 — Mandaqui, São Paulo/SP", city:"São Paulo", neighborhood:"Mandaqui", postalCode:"02401-400", coordinates:{latitude:-23.4944879,longitude:-46.6263702}, contact:{website:PROSANGUE}, donation:{bloodDonation:true, appointmentRecommended:true, appointmentUrl:"https://prosangue.hubglobe.com/entrar", openingHours:"Seg. a sex., 8h às 16h30. Confirme sábados e feriados."}, source:{institutionName:"Fundação Pró-Sangue",officialUrl:PROSANGUE,lastVerifiedAt:VERIFIED} }),
  row({ id:"pro-sangue-osasco", name:"Pró-Sangue — Posto Osasco", institutionName:"Fundação Pró-Sangue", type:"posto_coleta", management:"publico", address:address("Rua Ari Barroso","355","Presidente Altino","Osasco","06216-240"), fullAddress:"Rua Ari Barroso, 355 — Presidente Altino, Osasco/SP", city:"Osasco", neighborhood:"Presidente Altino", postalCode:"06216-240", coordinates:{latitude:-23.5249302,longitude:-46.771939}, contact:{website:PROSANGUE}, donation:{bloodDonation:true, appointmentRecommended:true, appointmentUrl:"https://prosangue.hubglobe.com/entrar", openingHours:"Consulte o horário oficial."}, source:{institutionName:"Fundação Pró-Sangue",officialUrl:PROSANGUE,lastVerifiedAt:VERIFIED} }),
  row({ id:"pro-sangue-barueri", name:"Pró-Sangue — Posto Barueri", institutionName:"Fundação Pró-Sangue", type:"posto_coleta", management:"publico", address:address("Alameda Xingu","245","Alphaville","Barueri","06455-030"), fullAddress:"Alameda Xingu, 245 — Alphaville, Barueri/SP", city:"Barueri", neighborhood:"Alphaville", postalCode:"06455-030", coordinates:{latitude:-23.5047763,longitude:-46.85439}, contact:{website:PROSANGUE}, donation:{bloodDonation:true, appointmentRecommended:true, appointmentUrl:"https://prosangue.hubglobe.com/entrar", openingHours:"Consulte o horário oficial."}, source:{institutionName:"Fundação Pró-Sangue",officialUrl:PROSANGUE,lastVerifiedAt:VERIFIED} }),

  row({ id:"colsan-mario-covas", name:"Hospital Estadual Mário Covas — COLSAN", institutionName:"COLSAN", donationLocationName:"Posto de coleta Hospital Estadual Mário Covas", type:"hospital_com_coleta", management:"publico", address:address("Rua Dr. Henrique Calderazzo","321","Paraíso","Santo André","09190-615"), fullAddress:"Rua Dr. Henrique Calderazzo, 321 — Paraíso, Santo André/SP", city:"Santo André", neighborhood:"Paraíso", postalCode:"09190-615", coordinates:{latitude:-23.670927,longitude:-46.5329851}, contact:{phone:"(11) 2324-5780 / 2324-5789",website:COLSAN}, donation:{bloodDonation:true, openingHours:"Seg. a sex., 7h30 às 14h30; sáb., 7h30 às 13h30 (exceto feriados).", schedule:{weekdays:{start:"07:30",end:"14:30"},saturday:{start:"07:30",end:"13:30"}}, saturdayService:true,sundayService:false,holidayService:false,parkingAvailable:true,freeParkingForDonors:true}, source:{institutionName:"COLSAN",officialUrl:COLSAN,lastVerifiedAt:VERIFIED} }),
  row({ id:"colsan-sbc", name:"Hemocentro Regional de São Bernardo do Campo", institutionName:"COLSAN", type:"hemocentro", management:"publico", address:address("Rua Pedro Jacobucci","440","Jardim das Américas","São Bernardo do Campo","09725-570"), fullAddress:"Rua Pedro Jacobucci, 440 — Jardim das Américas, São Bernardo do Campo/SP", city:"São Bernardo do Campo", neighborhood:"Jardim das Américas", postalCode:"09725-570", coordinates:{latitude:-23.6988835,longitude:-46.5554942}, contact:{phone:"(11) 2111-0007 / 2111-0008",website:COLSAN}, donation:{bloodDonation:true, openingHours:"Seg. a sex., 7h30 às 14h30; sáb., 7h30 às 13h30 (exceto feriados).", schedule:{weekdays:{start:"07:30",end:"14:30"},saturday:{start:"07:30",end:"13:30"}}, saturdayService:true,sundayService:false,holidayService:false,parkingAvailable:true,freeParkingForDonors:true}, source:{institutionName:"COLSAN",officialUrl:COLSAN,lastVerifiedAt:VERIFIED} }),
  row({ id:"colsan-scs", name:"Posto de Coleta São Caetano do Sul", institutionName:"COLSAN", type:"posto_coleta", management:"publico", address:address("Av. Vital Brasil Filho","300","Oswaldo Cruz","São Caetano do Sul","09540-420"), fullAddress:"Av. Vital Brasil Filho, 300 — Oswaldo Cruz, São Caetano do Sul/SP", city:"São Caetano do Sul", neighborhood:"Oswaldo Cruz", postalCode:"09540-420", coordinates:{latitude:-23.625496,longitude:-46.5640576}, contact:{phone:"(11) 2759-0888",website:COLSAN}, donation:{bloodDonation:true,openingHours:"Seg. a sáb., 7h30 às 13h (exceto feriados).",schedule:{weekdays:{start:"07:30",end:"13:00"},saturday:{start:"07:30",end:"13:00"}},saturdayService:true,sundayService:false,holidayService:false}, source:{institutionName:"COLSAN",officialUrl:COLSAN,lastVerifiedAt:VERIFIED} }),
  row({ id:"colsan-tatuape", name:"Hospital Municipal Dr. Cármino Caricchio — COLSAN", institutionName:"COLSAN", donationLocationName:"Posto de coleta do Hospital Municipal Dr. Cármino Caricchio", type:"hospital_com_coleta", management:"publico", address:address("Av. Celso Garcia","4815","Tatuapé","São Paulo","03069-000","entrada pela Rua Síria, 25"), fullAddress:"Av. Celso Garcia, 4.815 — entrada pela Rua Síria, 25 — Tatuapé, São Paulo/SP", city:"São Paulo", neighborhood:"Tatuapé", postalCode:"03069-000", coordinates:{latitude:-23.5329502,longitude:-46.5664411}, contact:{phone:"(11) 5178-1614 / 5178-1646",website:COLSAN}, donation:{bloodDonation:true,openingHours:"Seg. a sáb., 8h às 13h (exceto feriados).",schedule:{weekdays:{start:"08:00",end:"13:00"},saturday:{start:"08:00",end:"13:00"}},saturdayService:true,sundayService:false,holidayService:false,parkingAvailable:true,freeParkingForDonors:true}, source:{institutionName:"COLSAN",officialUrl:COLSAN,lastVerifiedAt:VERIFIED} }),
  row({ id:"colsan-hspm", name:"Hospital do Servidor Público Municipal — COLSAN", institutionName:"COLSAN", donationLocationName:"Posto de coleta do HSPM", type:"hospital_com_coleta", management:"publico", address:address("Rua Castro Alves","60","Aclimação","São Paulo","01532-000","4º andar"), fullAddress:"Rua Castro Alves, 60, 4º andar — Aclimação, São Paulo/SP", city:"São Paulo", neighborhood:"Aclimação", postalCode:"01532-000", coordinates:{latitude:-23.5673424,longitude:-46.639071}, contact:{phone:"(11) 2111-0006",website:COLSAN}, donation:{bloodDonation:true,openingHours:"Seg. a sáb., 8h às 12h30 (exceto feriados).",schedule:{weekdays:{start:"08:00",end:"12:30"},saturday:{start:"08:00",end:"12:30"}},saturdayService:true,sundayService:false,holidayService:false}, source:{institutionName:"COLSAN",officialUrl:COLSAN,lastVerifiedAt:VERIFIED} }),

  row({ id:"einstein-morumbi", name:"Banco de Sangue Einstein Morumbi", institutionName:"Hospital Israelita Albert Einstein", donationLocationName:"Banco de Sangue — Bloco D, 3º andar", type:"hospital_com_coleta", management:"filantropico", address:address("Av. Albert Einstein","701","Morumbi","São Paulo","05652-900","Bloco D, 3º andar"), fullAddress:"Av. Albert Einstein, 701, Bloco D, 3º andar — Morumbi, São Paulo/SP", city:"São Paulo", neighborhood:"Morumbi", postalCode:"05652-900", coordinates:{latitude:-23.600137,longitude:-46.7180156}, contact:{phone:"(11) 2151-0457",website:"https://www.einstein.br/n/vida-saudavel/doar-sangue-e-salvar-vidas"}, donation:{bloodDonation:true,appointmentRequired:true,appointmentUrl:"https://www.einstein.br/n/vida-saudavel/doar-sangue-e-salvar-vidas",openingHours:"Atendimento mediante agendamento; confirme o horário oficial."}, source:{institutionName:"Hospital Israelita Albert Einstein",officialUrl:"https://www.einstein.br/n/vida-saudavel/doar-sangue-e-salvar-vidas",lastVerifiedAt:VERIFIED} }),
  row({ id:"bp-banco-sangue", name:"Banco de Sangue BP", institutionName:"BP — A Beneficência Portuguesa de São Paulo", donationLocationName:"Banco de Sangue BP — Portaria 2", type:"hospital_com_coleta", management:"filantropico", address:address("Rua Maestro Cardim","769","Bela Vista","São Paulo","01323-001","Portaria 2"), fullAddress:"Rua Maestro Cardim, 769, Portaria 2 — Bela Vista, São Paulo/SP", city:"São Paulo", neighborhood:"Bela Vista", postalCode:"01323-001", coordinates:{latitude:-23.5674997,longitude:-46.6415425}, contact:{phone:"(11) 3505-4782 / 3505-4783",website:"https://www.bp.org.br/institucional/banco-de-sangue"}, donation:{bloodDonation:true,openingHours:"Todos os dias, 7h às 18h, inclusive feriados.",schedule:{weekdays:{start:"07:00",end:"18:00"},saturday:{start:"07:00",end:"18:00"},sunday:{start:"07:00",end:"18:00"},holidays:{start:"07:00",end:"18:00"}},saturdayService:true,sundayService:true,holidayService:true,parkingAvailable:true,freeParkingForDonors:true}, source:{institutionName:"BP",officialUrl:"https://www.bp.org.br/institucional/banco-de-sangue",lastVerifiedAt:VERIFIED} }),
  row({ id:"gsh-paraiso", name:"Banco de Sangue de São Paulo — GSH", institutionName:"Grupo GSH", donationLocationName:"Unidade Paraíso", type:"banco_sangue", management:"privado", address:address("Rua Tomás Carvalhal","711","Paraíso","São Paulo","04006-002"), fullAddress:"Rua Tomás Carvalhal, 711 — Paraíso, São Paulo/SP", city:"São Paulo", neighborhood:"Paraíso", postalCode:"04006-002", coordinates:{latitude:-23.575378,longitude:-46.6420129}, contact:{phone:"(11) 3373-2000 / 3373-2001",whatsapp:"(11) 97117-3886",website:"https://www.doesanguedoevida.com.br/banco-de-sangue-sao-paulo-jd-paulista"}, donation:{bloodDonation:true,appointmentRequired:false,appointmentUrl:"https://www.doesanguedoevida.com.br/banco-de-sangue-sao-paulo-jd-paulista",openingHours:"Todos os dias, 7h às 18h, inclusive feriados.",schedule:{weekdays:{start:"07:00",end:"18:00"},saturday:{start:"07:00",end:"18:00"},sunday:{start:"07:00",end:"18:00"},holidays:{start:"07:00",end:"18:00"}},saturdayService:true,sundayService:true,holidayService:true,parkingAvailable:true,freeParkingForDonors:true}, source:{institutionName:"Banco de Sangue de São Paulo — Grupo GSH",officialUrl:"https://www.doesanguedoevida.com.br/banco-de-sangue-sao-paulo-jd-paulista",lastVerifiedAt:VERIFIED} }),
  row({ id:"pulsa-samaritano", name:"Banco de Sangue — Unidade Samaritano", institutionName:"Grupo Pulsa", donationLocationName:"Unidade Samaritano Higienópolis", type:"hospital_com_coleta", management:"privado", address:address("Rua Conselheiro Brotero","1486","Higienópolis","São Paulo","01232-010"), fullAddress:"Rua Conselheiro Brotero, 1.486 — Higienópolis, São Paulo/SP", city:"São Paulo", neighborhood:"Higienópolis", postalCode:"01232-010", coordinates:{latitude:-23.5390715,longitude:-46.6620335}, contact:{phone:"(11) 3821-5852",whatsapp:"(11) 94502-9697",website:"https://pulsandovidas.com.br/sp/"}, donation:{bloodDonation:true,openingHours:"Seg. a sex., 8h às 13h.",schedule:{weekdays:{start:"08:00",end:"13:00"}},saturdayService:false,sundayService:false,holidayService:false,parkingAvailable:true}, source:{institutionName:"Grupo Pulsa",officialUrl:"https://pulsandovidas.com.br/sp/",lastVerifiedAt:VERIFIED} }),
  row({ id:"pulsa-santo-amaro", name:"Banco de Sangue — Unidade Santo Amaro", institutionName:"Grupo Pulsa", donationLocationName:"Unidade Santo Amaro", type:"banco_sangue", management:"privado", address:address("Rua Iguatinga","382","Santo Amaro","São Paulo","04744-040"), fullAddress:"Rua Iguatinga, 382 — Santo Amaro, São Paulo/SP", city:"São Paulo", neighborhood:"Santo Amaro", postalCode:"04744-040", coordinates:{latitude:-23.6567965,longitude:-46.7049684}, contact:{phone:"(11) 5521-4013",whatsapp:"(11) 98916-9528",website:"https://pulsandovidas.com.br/sp/"}, donation:{bloodDonation:true,openingHours:"Seg. a sex., 8h às 16h30; sáb., 8h às 16h.",schedule:{weekdays:{start:"08:00",end:"16:30"},saturday:{start:"08:00",end:"16:00"}},saturdayService:true,sundayService:false,holidayService:false,parkingAvailable:true}, source:{institutionName:"Grupo Pulsa",officialUrl:"https://pulsandovidas.com.br/sp/",lastVerifiedAt:VERIFIED} }),
  row({ id:"instituto-hoc", name:"Instituto HOC de Hemoterapia", institutionName:"Instituto HOC / Hospital Alemão Oswaldo Cruz", donationLocationName:"Instituto HOC de Hemoterapia", type:"hospital_com_coleta", management:"privado", address:address("Rua Treze de Maio","1815","Bela Vista","São Paulo","01327-001","entrada também pela Rua João Julião, 331"), fullAddress:"Rua Treze de Maio, 1.815 — Bela Vista, São Paulo/SP (entrada também pela Rua João Julião, 331)", city:"São Paulo", neighborhood:"Bela Vista", postalCode:"01327-001", coordinates:{latitude:-23.5690395,longitude:-46.643808}, contact:{phone:"0800 772 1227 / (11) 3286-7372",whatsapp:"(11) 99285-3684",website:"https://www.institutohoc.com.br/doe-sangue.html"}, donation:{bloodDonation:true,appointmentRecommended:true,appointmentUrl:"https://www.institutohoc.com.br/doe-sangue.html",openingHours:"Seg. a sex., 7h às 18h; sáb., 8h às 13h (exceto feriados).",schedule:{weekdays:{start:"07:00",end:"18:00"},saturday:{start:"08:00",end:"13:00"}},saturdayService:true,sundayService:false,holidayService:false,parkingAvailable:true,freeParkingForDonors:true}, source:{institutionName:"Instituto HOC",officialUrl:"https://www.institutohoc.com.br/doe-sangue.html",lastVerifiedAt:VERIFIED} }),
  row({ id:"santa-marcelina", name:"Banco de Sangue Santa Marcelina", institutionName:"Hospital Santa Marcelina", donationLocationName:"Banco de Sangue Santa Marcelina", type:"hospital_com_coleta", management:"filantropico", address:address("Rua Harry Dannemberg","473","Itaquera","São Paulo","08270-010"), fullAddress:"Rua Harry Dannemberg, 473 — Itaquera, São Paulo/SP", city:"São Paulo", neighborhood:"Itaquera", postalCode:"08270-010", coordinates:{latitude:-23.555951,longitude:-46.4650071}, contact:{phone:"(11) 2070-6081",website:"https://santamarcelina.org/banco-de-doacao-de-sangue/"}, donation:{bloodDonation:true,plateletDonation:true,openingHours:"Seg. a sex., 7h às 16h; sáb., 7h às 12h. Fechado domingos e feriados.",schedule:{weekdays:{start:"07:00",end:"16:00"},saturday:{start:"07:00",end:"12:00"}},saturdayService:true,sundayService:false,holidayService:false,parkingAvailable:true,freeParkingForDonors:true}, source:{institutionName:"Santa Marcelina Saúde",officialUrl:"https://santamarcelina.org/banco-de-doacao-de-sangue/",lastVerifiedAt:VERIFIED} }),
  row({ id:"iamspe-hspe", name:"Banco de Sangue do HSPE", institutionName:"IAMSPE — Hospital do Servidor Público Estadual", donationLocationName:"Banco de Sangue do HSPE", type:"hospital_com_coleta", management:"publico", address:address("Rua Pedro de Toledo","1800","Vila Clementino","São Paulo","04039-004"), fullAddress:"Rua Pedro de Toledo, 1.800 — Vila Clementino, São Paulo/SP", city:"São Paulo", neighborhood:"Vila Clementino", postalCode:"04039-004", coordinates:{latitude:-23.5983567,longitude:-46.6434186}, contact:{website:"https://www.iamspe.sp.gov.br/iamspe/espaco_do_usuario/hspe/subpaginas/doacao_de_sangue"}, donation:{bloodDonation:true,openingHours:"Seg. a sex., 9h às 16h; sáb., 8h às 16h.",schedule:{weekdays:{start:"09:00",end:"16:00"},saturday:{start:"08:00",end:"16:00"}},saturdayService:true,sundayService:false}, source:{institutionName:"IAMSPE",officialUrl:"https://www.iamspe.sp.gov.br/iamspe/espaco_do_usuario/hspe/subpaginas/doacao_de_sangue",lastVerifiedAt:VERIFIED} }),

  row({ id:"colsan-ermelino-matarazzo", name:"Hospital Municipal Prof. Dr. Alípio Corrêa Netto — COLSAN", institutionName:"COLSAN", donationLocationName:"Posto de coleta Ermelino Matarazzo", type:"hospital_com_coleta", management:"publico", address:address("Rua Gildo Lao","1989","Ermelino Matarazzo","São Paulo","03807-230"), fullAddress:"Rua Gildo Lao, 1.989 — Ermelino Matarazzo, São Paulo/SP", city:"São Paulo", neighborhood:"Ermelino Matarazzo", postalCode:"03807-230", coordinates:{latitude:-23.4998363,longitude:-46.4724411}, contact:{phone:"(11) 5178-2306 / 5178-2087",website:COLSAN}, donation:{bloodDonation:true,openingHours:"Seg. a sáb., 8h às 13h (exceto feriados).",schedule:{weekdays:{start:"08:00",end:"13:00"},saturday:{start:"08:00",end:"13:00"}},saturdayService:true,sundayService:false,holidayService:false}, source:{institutionName:"COLSAN",officialUrl:COLSAN,lastVerifiedAt:VERIFIED} }),
  row({ id:"sirio-libanes-bela-vista", name:"Banco de Sangue Sírio-Libanês", institutionName:"Hospital Sírio-Libanês", donationLocationName:"Banco de Sangue — Unidade Bela Vista", type:"hospital_com_coleta", management:"filantropico", address:address("Rua Dona Adma Jafet","91","Bela Vista","São Paulo","01308-050"), fullAddress:"Rua Dona Adma Jafet, 91 — Bela Vista, São Paulo/SP", city:"São Paulo", neighborhood:"Bela Vista", postalCode:"01308-050", coordinates:{latitude:-23.5569,longitude:-46.6544}, contact:{phone:"(11) 3394-5260",whatsapp:"(11) 98899-5391 / 99303-9292 / 96859-9699",website:"https://hospitalsiriolibanes.org.br/doe-sangue"}, donation:{bloodDonation:true,plateletDonation:true,openingHours:"Seg. a sáb., 7h às 16h (exceto feriados).",schedule:{weekdays:{start:"07:00",end:"16:00"},saturday:{start:"07:00",end:"16:00"}},saturdayService:true,sundayService:false,holidayService:false,appointmentRecommended:true}, source:{institutionName:"Hospital Sírio-Libanês",officialUrl:"https://hospitalsiriolibanes.org.br/doe-sangue",lastVerifiedAt:VERIFIED} }),
  row({ id:"accamargo-castro-alves", name:"Banco de Sangue A.C.Camargo Cancer Center", institutionName:"A.C.Camargo Cancer Center", donationLocationName:"Banco de Sangue — Unidade Castro Alves", type:"hospital_com_coleta", management:"filantropico", address:address("Rua Castro Alves","131","Aclimação","São Paulo","01532-001"), fullAddress:"Rua Castro Alves, 131 — Aclimação, São Paulo/SP", city:"São Paulo", neighborhood:"Aclimação", postalCode:"01532-001", coordinates:{latitude:-23.566819348,longitude:-46.638754606}, contact:{phone:"(11) 2189-5000, opção 5",website:"https://accamargo.org.br/apoie-nossa-causa/banco-de-sangue"}, donation:{bloodDonation:true,plateletDonation:true,appointmentRecommended:true,appointmentUrl:"https://accamargo.org.br/form/agendamento-doacao-sangue",openingHours:"Seg. a sex., 8h às 17h; sáb., 8h às 15h. Fechado domingos e feriados.",schedule:{weekdays:{start:"08:00",end:"17:00"},saturday:{start:"08:00",end:"15:00"}},saturdayService:true,sundayService:false,holidayService:false}, source:{institutionName:"A.C.Camargo Cancer Center",officialUrl:"https://accamargo.org.br/apoie-nossa-causa/banco-de-sangue",lastVerifiedAt:VERIFIED} }),
  row({ id:"sao-lucas-shopping-mais", name:"Hemocentro São Lucas — Shopping Mais", institutionName:"Hemocentro São Lucas", donationLocationName:"Unidade Shopping Mais", type:"hemocentro", management:"privado", address:address("Rua Amador Bueno","229","Santo Amaro","São Paulo","04752-005"), fullAddress:"Rua Amador Bueno, 229 — Santo Amaro, São Paulo/SP", city:"São Paulo", neighborhood:"Santo Amaro", postalCode:"04752-005", coordinates:{latitude:-23.6529081,longitude:-46.7109931}, contact:{phone:"(11) 3660-6000",website:"https://hemocentrosaolucas.com.br/hemocentro-shopping-mais/"}, donation:{bloodDonation:true,appointmentRequired:false,openingHours:"Seg. a sáb., 8h às 19h.",schedule:{weekdays:{start:"08:00",end:"19:00"},saturday:{start:"08:00",end:"19:00"}},saturdayService:true,sundayService:false,parkingAvailable:true,freeParkingForDonors:true}, source:{institutionName:"Hemocentro São Lucas",officialUrl:"https://hemocentrosaolucas.com.br/hemocentro-shopping-mais/",lastVerifiedAt:VERIFIED} }),
  row({ id:"hospital-sao-paulo-unifesp", name:"Hemocentro do Hospital São Paulo", institutionName:"Hospital São Paulo / SPDM / UNIFESP", donationLocationName:"Hemocentro do Hospital São Paulo", type:"hospital_com_coleta", management:"filantropico", address:address("Rua Dr. Diogo de Faria","824","Vila Clementino","São Paulo","04037-002","esquina com a Rua dos Otonis"), fullAddress:"Rua Dr. Diogo de Faria, 824, esquina com a Rua dos Otonis — Vila Clementino, São Paulo/SP", city:"São Paulo", neighborhood:"Vila Clementino", postalCode:"04037-002", coordinates:{latitude:-23.595559,longitude:-46.644549}, contact:{phone:"(11) 5576-4240, opção 1",website:"https://sites.google.com/huhsp.org.br/hemocentro-hsp"}, donation:{bloodDonation:true,openingHours:"Seg. a sex., 8h às 17h30; sáb., 8h às 12h (exceto feriados).",schedule:{weekdays:{start:"08:00",end:"17:30"},saturday:{start:"08:00",end:"12:00"}},saturdayService:true,sundayService:false,holidayService:false}, source:{institutionName:"Hospital São Paulo / SPDM",officialUrl:"https://sites.google.com/huhsp.org.br/hemocentro-hsp",lastVerifiedAt:VERIFIED} }),
  row({ id:"santa-casa-hemocentro", name:"Hemocentro da Santa Casa de São Paulo", institutionName:"Santa Casa de Misericórdia de São Paulo", donationLocationName:"Hemocentro", type:"hemocentro", management:"filantropico", address:address("Rua Marquês de Itu","579","Vila Buarque","São Paulo","01223-001"), fullAddress:"Rua Marquês de Itu, 579 — Vila Buarque, São Paulo/SP", city:"São Paulo", neighborhood:"Vila Buarque", postalCode:"01223-001", coordinates:{latitude:-23.543883,longitude:-46.6499773}, contact:{phone:"(11) 2176-7155",website:"https://santacasasp.org.br/onde-posso-doar/"}, donation:{bloodDonation:true,plateletDonation:true,openingHours:"Seg. a sex., 7h às 17h; sáb., 7h às 15h.",schedule:{weekdays:{start:"07:00",end:"17:00"},saturday:{start:"07:00",end:"15:00"}},saturdayService:true,sundayService:false,parkingAvailable:true,freeParkingForDonors:true}, source:{institutionName:"Santa Casa de Misericórdia de São Paulo",officialUrl:"https://santacasasp.org.br/onde-posso-doar/",lastVerifiedAt:VERIFIED} }),
  row({ id:"santa-casa-sao-luiz-gonzaga", name:"Posto de Coleta Hospital São Luiz Gonzaga", institutionName:"Santa Casa de Misericórdia de São Paulo", donationLocationName:"Posto de coleta Hospital São Luiz Gonzaga", type:"hospital_com_coleta", management:"filantropico", address:address("Rua Michel Ouchana","94","Jaçanã","São Paulo","02276-140"), fullAddress:"Rua Michel Ouchana, 94 — Jaçanã, São Paulo/SP", city:"São Paulo", neighborhood:"Jaçanã", postalCode:"02276-140", coordinates:{latitude:-23.45895,longitude:-46.58202}, contact:{phone:"(11) 3466-1000",website:"https://santacasasp.org.br/onde-posso-doar/"}, donation:{bloodDonation:true,openingHours:"Seg. a sex., 7h às 11h. Confirme antes de ir.",schedule:{weekdays:{start:"07:00",end:"11:00"}},saturdayService:false,sundayService:false}, source:{institutionName:"Santa Casa de Misericórdia de São Paulo",officialUrl:"https://santacasasp.org.br/onde-posso-doar/",lastVerifiedAt:VERIFIED} }),
  row({ id:"edmundo-vasconcelos", name:"Banco de Sangue Hospital Edmundo Vasconcelos", institutionName:"Hospital Edmundo Vasconcelos / Grupo Santa Joana", donationLocationName:"Banco de Sangue", type:"hospital_com_coleta", management:"privado", address:address("Rua Borges Lagoa","1450","Vila Clementino","São Paulo","04038-905"), fullAddress:"Rua Borges Lagoa, 1.450 — Vila Clementino, São Paulo/SP", city:"São Paulo", neighborhood:"Vila Clementino", postalCode:"04038-905", coordinates:{latitude:-23.59698,longitude:-46.64555}, contact:{phone:"(11) 5080-4435",website:"https://santajoana.com.br/banco-de-sangue/"}, donation:{bloodDonation:true,openingHours:"Seg. a sex., 8h às 12h (exceto feriados).",schedule:{weekdays:{start:"08:00",end:"12:00"}},saturdayService:false,sundayService:false,holidayService:false}, source:{institutionName:"Grupo Santa Joana",officialUrl:"https://santajoana.com.br/banco-de-sangue/",lastVerifiedAt:VERIFIED} }),
  row({ id:"sao-lucas-guarulhos", name:"Hemocentro São Lucas — Guarulhos", institutionName:"Hemocentro São Lucas", donationLocationName:"Unidade Guarulhos", type:"hemocentro", management:"privado", address:address("Rua Santo Antônio","95","Centro","Guarulhos","07110-110"), fullAddress:"Rua Santo Antônio, 95 — Centro, Guarulhos/SP", city:"Guarulhos", neighborhood:"Centro", postalCode:"07110-110", coordinates:{latitude:-23.4677777,longitude:-46.5248405}, contact:{phone:"(11) 3660-6000",website:"https://hemocentrosaolucas.com.br/hemocentro-guarulhos/"}, donation:{bloodDonation:true,appointmentRequired:false,openingHours:"Seg. a sáb., 7h às 18h.",schedule:{weekdays:{start:"07:00",end:"18:00"},saturday:{start:"07:00",end:"18:00"}},saturdayService:true,sundayService:false,parkingAvailable:true,freeParkingForDonors:true}, source:{institutionName:"Hemocentro São Lucas",officialUrl:"https://hemocentrosaolucas.com.br/hemocentro-guarulhos/",lastVerifiedAt:VERIFIED} }),
  row({ id:"gsh-santo-andre", name:"Banco de Sangue de Santo André — GSH", institutionName:"Grupo GSH", donationLocationName:"Unidade Santo André", type:"banco_sangue", management:"privado", address:address("Av. Dom Pedro II","877","Jardim","Santo André","09080-110"), fullAddress:"Av. Dom Pedro II, 877 — Jardim, Santo André/SP", city:"Santo André", neighborhood:"Jardim", postalCode:"09080-110", coordinates:{latitude:-23.65413,longitude:-46.53269}, contact:{phone:"(11) 4434-8200",whatsapp:"(11) 96910-2488",website:"https://www.doesanguedoevida.com.br/banco-de-sangue-de-santo-andre"}, donation:{bloodDonation:true,appointmentRequired:false,appointmentUrl:"https://www.doesanguedoevida.com.br/banco-de-sangue-de-santo-andre",openingHours:"Seg. a sáb., 7h às 12h.",schedule:{weekdays:{start:"07:00",end:"12:00"},saturday:{start:"07:00",end:"12:00"}},saturdayService:true,sundayService:false,parkingAvailable:true,freeParkingForDonors:true}, source:{institutionName:"Grupo GSH",officialUrl:"https://www.doesanguedoevida.com.br/banco-de-sangue-de-santo-andre",lastVerifiedAt:VERIFIED} }),
  row({ id:"sao-lucas-sao-bernardo", name:"Hemocentro São Lucas — São Bernardo", institutionName:"Hemocentro São Lucas", donationLocationName:"Unidade São Bernardo", type:"hemocentro", management:"privado", address:address("Rua Coral","369","Jardim das Américas","São Bernardo do Campo","09725-730"), fullAddress:"Rua Coral, 369 — Jardim das Américas, São Bernardo do Campo/SP", city:"São Bernardo do Campo", neighborhood:"Jardim das Américas", postalCode:"09725-730", coordinates:{latitude:-23.6936121,longitude:-46.5565728}, contact:{phone:"(11) 3660-6000",website:"https://hemocentrosaolucas.com.br/hemocentro-sao-bernardo/"}, donation:{bloodDonation:true,appointmentRequired:false,openingHours:"Seg. a sex., 8h às 16h15; sáb., 8h às 11h30.",schedule:{weekdays:{start:"08:00",end:"16:15"},saturday:{start:"08:00",end:"11:30"}},saturdayService:true,sundayService:false,parkingAvailable:true,freeParkingForDonors:true}, source:{institutionName:"Hemocentro São Lucas",officialUrl:"https://hemocentrosaolucas.com.br/hemocentro-sao-bernardo/",lastVerifiedAt:VERIFIED} }),
  row({ id:"colsan-maua", name:"Posto de Coleta Mauá — COLSAN", institutionName:"COLSAN", donationLocationName:"Posto de coleta Mauá", type:"posto_coleta", management:"filantropico", address:address("Rua Luiz Lacava","229","Vila Bocaina","Mauá","09310-080"), fullAddress:"Rua Luiz Lacava, 229 — Vila Bocaina, Mauá/SP", city:"Mauá", neighborhood:"Vila Bocaina", postalCode:"09310-080", coordinates:{latitude:-23.6686648,longitude:-46.4579699}, contact:{phone:"(11) 2564-1200",website:COLSAN}, donation:{bloodDonation:true,openingHours:"Seg. a sáb., 7h30 às 13h (exceto feriados).",schedule:{weekdays:{start:"07:30",end:"13:00"},saturday:{start:"07:30",end:"13:00"}},saturdayService:true,sundayService:false,holidayService:false}, source:{institutionName:"COLSAN",officialUrl:COLSAN,lastVerifiedAt:VERIFIED} }),
  row({ id:"hospital-estadual-diadema", name:"Posto de Coleta Hospital Estadual de Diadema", institutionName:"Hospital Estadual de Diadema / SPDM", donationLocationName:"Agência Transfusional — Posto de coleta", type:"hospital_com_coleta", management:"publico", address:address("Rua José Bonifácio","1641","Serraria","Diadema","09980-150"), fullAddress:"Rua José Bonifácio, 1.641 — Serraria, Diadema/SP", city:"Diadema", neighborhood:"Serraria", postalCode:"09980-150", coordinates:{latitude:-23.70657,longitude:-46.6089}, contact:{phone:"(11) 3583-1475",website:"https://hed.spdmafiliadas.org.br/agencia-transfusional-v2/"}, donation:{bloodDonation:true,openingHours:"Seg. a sex., 8h às 14h.",schedule:{weekdays:{start:"08:00",end:"14:00"}},saturdayService:false,sundayService:false}, source:{institutionName:"Hospital Estadual de Diadema / SPDM",officialUrl:"https://hed.spdmafiliadas.org.br/agencia-transfusional-v2/",lastVerifiedAt:VERIFIED} }),

  // Expansão de cobertura geográfica — novo desde a revisão de 28/08/2026.
  row({ id:"hgp-taboao-da-serra", name:"Hospital Geral de Pirajussara — HGP", institutionName:"Hospital Geral de Pirajussara / SPDM", donationLocationName:"Banco de Sangue do HGP", type:"hospital_com_coleta", management:"publico", address:address("Av. Ibirama","1214","Jardim São Judas","Taboão da Serra","06785-300"), fullAddress:"Av. Ibirama, 1.214 — Jardim São Judas, Taboão da Serra/SP", city:"Taboão da Serra", neighborhood:"Jardim São Judas", postalCode:"06785-300", coordinates:{latitude:-23.6411,longitude:-46.8095}, contact:{phone:"(11) 4138-9400"}, donation:{bloodDonation:true, openingHours:"Seg. a qui., 7h às 12h30 e 14h às 16h; sex., 7h às 12h30.", saturdayService:false, sundayService:false}, source:{institutionName:"Prefeitura de Taboão da Serra",officialUrl:"https://www.ts.sp.gov.br/portal/noticias/0/3/1074/hospital-geral-do-pirajussara-esta-precisando-de-doacao-de-sangue",lastVerifiedAt:VERIFIED} }),
];

export const PUBLIC_DONATION_CENTERS = DONATION_CENTERS.filter((center) => center.active && center.verificationStatus === "verified");
